Added Heroku support
filippofinke/mood-meter pull request #3
Opened 2022-05-13 16:33 UTC by anjannair

This should fix #1 
The Heroku deploy button will only work after being merged because it requires the `app.json` in the repository. Here is [link](https://devcenter.heroku.com/articles/heroku-button) to the docs for that.

You can test the button here (this is linked to my repository as it contains the `app.json`)
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/anjannair/mood-meter)

Removed webhook url from config and added it to `.env` which user has to input. This will help with easy deployment to Heroku.

2022-05-13 16:39 UTC, filippofinke commented
Thanks for the contribution!

But in order to be accepted I think we should transform the config.js file into environment variables because at the moment on Heroku it shows the error of renaming the configuration file "config.sample.js" to "config.js".

2022-05-13 16:41 UTC, anjannair commented
Oh yeah definitely! I do not think its necessary to keep the config as sample anymore too

2022-05-13 17:32 UTC, anjannair commented
@filippofinke can you check if this is working appropriately?
Do not merge yet as I am yet to integrate config.json completely into env

2022-05-13 17:56 UTC, anjannair commented
@filippofinke alright feel free to poke around the code. I am unsure if you would like to include colors in the environment variables or not hence I have left that as it is.

If you are confused what is EJS just check out - https://ejs.co/ (PS - It is plain and simple HTML with a small twist and a different extension)

2022-05-14 09:02 UTC, anjannair commented
@filippofinke final push done! You can now merge it!

P.S - The test button to deploy can be found in the main comment of this PR

2022-05-17 14:55 UTC, filippofinke commented
I think that since you added some kind of server side rendering the fetch request for the mood is not needed anymore.

Also I think that also the emojis should be an env variable.

2022-05-17 15:14 UTC, anjannair commented
> I think that since you added some kind of server side rendering the fetch request for the mood is not needed anymore.
> 
> Also I think that also the emojis should be an env variable.

So do you like the server side rendering or do you want me to remove it?

Should I add the emojis to the env variable?

2022-05-17 15:34 UTC, filippofinke requested changes

2022-05-17 15:34 UTC, filippofinke commented on config.json
>      "emojis": [
We can remove the emojis array and create a new env variable.

2022-05-17 15:34 UTC, filippofinke commented on public/js/index.js
>    config = await fetch("/config").then((r) => r.json());
We can remove this fetch for the cofing and instead use template variables from ejs.

2022-05-17 15:34 UTC, filippofinke commented on public/js/index.js
>    let mood = await fetch("/mood").then((r) => r.json());
Same here, we can remove the fetch request and use instead an ejs variable.

2022-05-17 15:34 UTC, filippofinke commented on server.js
> +  res.render("index",{title:process.env.TITLE,bgColor:process.env.bgColor,textColor:process.env.textColor,sliderThumbColor:process.env.sliderThumbColor,sliderBgColor:process.env.sliderBgColor});
Please, format the code correctly.

2022-05-17 15:34 UTC, filippofinke commented on views/index.ejs
> +  </script>
I am not sure if this is the best way to do it. I have never used eJs before, there isn't another way to change the css with eJs?

2022-05-17 15:35 UTC, filippofinke commented
> > I think that since you added some kind of server side rendering the fetch request for the mood is not needed anymore.
> > Also I think that also the emojis should be an env variable.
> 
> So do you like the server side rendering or do you want me to remove it?
> 
> Should I add the emojis to the env variable?

Yes, we can keep the server side rendering and remove all the client fetches.

Yes, this way we remove the config.js file and use only env variables.

2023-04-23 19:31 UTC, closed without merging